const regionsRU = [
    {
        thumbnail: "/images/regions/vn.jpg",
        title: "Винница",
        slug: "vinnycya",
        mapId: "vinnytsia",
        subtitle: "",
        description:
            "На территории Винницкой области реализованы все отрасли сельского хозяйства Украины. Но среди сельхозпредприятий основными все же являются производство молока и мяса (животноводство), выращивание сахарной свеклы, ячменя, пшеницы, кукурузы (растениеводство). Почти 25% сахарных посевов Украины приходится на Винницкую область. Ведущие показатели среди областей Украины здесь также занимает производство овощей. Хорошо развиты виноградарство и садоводство. Также присутствует редкость среди других областей Украины - выращивание хмеля.",
        oblast: "Винницкая область",
        locations: [
            { slug: "vinnitsa", title: "Винницкий район" },
            { slug: "hnivan", title: "город Гнивань", parent: "vinnitsa" },
            { slug: "illinetsky", title: "Ильинецкий район", parent: "vinnitsa" },
            { slug: "lypovetsky", title: "Липовецкий район", parent: "vinnitsa" },
            { slug: "litinsky", title: "Литинский район", parent: "vinnitsa" },
            { slug: "nemirovsky", title: "Немировский район", parent: "vinnitsa" },
            { slug: "orativ", title: "Оратовский район", parent: "vinnitsa" },
            { slug: "pohrebishche", title: "Погребищенский район", parent: "vinnitsa" },
            { slug: "tyvriv", title: "Тывровский район", parent: "vinnitsa" },
            { slug: "turbiv", title: "Турбовский район", parent: "vinnitsa" },
            { slug: "gaissin", title: "Гайсинский район" },
            { slug: "bershad", title: "Бершадский район", parent: "gaissin" },
            { slug: "ladizhin", title: "город Ладыжин", parent: "gaissin" },
            { slug: "teplichi", title: "Теплицкий район", parent: "gaissin" },
            { slug: "trostyanets", title: "Тростянецкий район", parent: "gaissin" },
            { slug: "chechelnytsky", title: "Чечельницкий район", parent: "gaissin" },
            { slug: "zhmerynka", title: "Жмеринский район" },
            { slug: "barsky", title: "Барский район", parent: "zhmerynka" },
            { slug: "shargorod", title: "Шаргородский район", parent: "zhmerynka" },
            { slug: "mohyliv-podilsky", title: "Могилев-Подольский район" },
            {
                slug: "murovankurilovetsky",
                title: "Мурованокуриловецкий район",
                parent: "mohyliv-podilsky",
            },
            { slug: "chernive", title: "Черновицкий район", parent: "mohyliv-podilsky" },
            { slug: "yampil", title: "Ямпольский район", parent: "mohyliv-podilsky" },
            { slug: "tulchyn", title: "Тульчинский район" },
            { slug: "bratslav", title: "Брацлав район", parent: "tulchyn" },
            { slug: "vapnyarka", title: "Вапнярка район", parent: "tulchyn" },
            { slug: "kryzhopilsky", title: "Крыжопольский район", parent: "tulchyn" },
            { slug: "pishchansky", title: "Песчанский район", parent: "tulchyn" },
            { slug: "tomashpilsky", title: "Томашпольский район", parent: "tulchyn" },
            { slug: "khmilnytsky", title: "Хмельницкий район" },
            { slug: "kalynivsky", title: "Калиновский район", parent: "khmilnytsky" },
            { slug: "kozyatyn", title: "Казатинский район", parent: "khmilnytsky" },
        ],
    },
    {
        thumbnail: "/images/regions/vl.jpg",
        title: "Волынь",
        slug: "volyn",
        mapId: "volyn",
        subtitle: "",
        description:
            "В экономике Волынской области 50% совокупного продукта обеспечивает аграрно-промышленный сектор. Зерновые и овощные культуры (растениеводство) являются основными специализациями в сельском хозяйстве области. Выращивается лен. Животноводство базируется на мясо-молочном направлении.",
        oblast: "Волынская область",
        locations: [
            { slug: "volodymyr-volynsky", title: "Владимир-Волынский район" },
            {
                slug: "ivanychivsky",
                title: "Иваничевский район",
                parent: "volodymyr-volynsky",
            },
            { slug: "lokachynsky", title: "Локачинский район", parent: "volodymyr-volynsky" },
            {
                slug: "novovolynsky",
                title: "Нововолынский район",
                parent: "volodymyr-volynsky",
            },
            { slug: "ustiluh", title: "Устилуг", parent: "volodymyr-volynsky" },
            { slug: "kamin-kashyrsky", title: "Камень-Каширский район" },
            { slug: "liubeshivsky", title: "Любешевский район", parent: "kamin-kashyrsky" },
            { slug: "manevytsky", title: "Маневицкий район", parent: "kamin-kashyrsky" },
            { slug: "kovel", title: "Ковельский район" },
            { slug: "liubomlsky", title: "Любомльский район", parent: "kovel" },
            { slug: "ratnivsky", title: "Ратновский район", parent: "kovel" },
            { slug: "starovyzhivsky", title: "Старовыжевский район", parent: "kovel" },
            { slug: "turiysky", title: "Турийский район", parent: "kovel" },
            { slug: "shatsky", title: "Шацкий район", parent: "kovel" },
            { slug: "lutsk", title: "Луцкий район" },
            { slug: "berestechko", title: "Берестечко", parent: "lutsk" },
            { slug: "horokhivsky", title: "Гороховский район", parent: "lutsk" },
            { slug: "kivertsivsky", title: "Киверцовский район", parent: "lutsk" },
            { slug: "rozhysche", title: "Рожищенский район", parent: "lutsk" },
            { slug: "olyka", title: "Олыка", parent: "lutsk" },
            { slug: "torchyn", title: "Торчин", parent: "lutsk" },
            { slug: "tsuman", title: "Цумань", parent: "lutsk" },
        ],
    },
    {
        thumbnail: "/images/regions/dp.jpg",
        title: "Днепр",
        slug: "dnipro",
        mapId: "dnipropetrovsk",
        subtitle: "",
        description:
            "В Днепропетровской области сельское хозяйство, по производству товаров и услуг, занимает второе место после промышленности. Наиболее активные направления в сельском хозяйстве Днепропетровщины - это выращивание птицы, производство мясо-молочной продукции (животноводство). В растениеводстве наиболее активно выращивают зерновые, технические и овощные культуры. Многие предприятия, работающие в сфере сельского хозяйства, используют инновационные технологии обработки почвы и выращивания урожая. В основном эти технологии применяются при выращивании сахарной свеклы, а также зерновых культур и подсолнечника.",
        oblast: "Днепропетровская область",
        locations: [
            {
                slug: "dniprovsky",
                title: "Днепровский район",
            },
            { slug: "novopokrovske", title: "Новопокровское", parent: "dniprovsky" },
            { slug: "obukhivka", title: "Обуховка", parent: "dniprovsky" },
            { slug: "slobozhanske", title: "Слобожанское", parent: "dniprovsky" },
            { slug: "pidhorodnenske", title: "Подгородненское", parent: "dniprovsky" },
            { slug: "petrikivsky", title: "Петриковский", parent: "dniprovsky" },
            { slug: "tsarychansky", title: "Царичанский район", parent: "dniprovsky" },
            { slug: "kamiansky", title: "Каменский район" },
            {
                slug: "verkhnedniprovsky",
                title: "Верхнеднепровский район",
                parent: "kamiansky",
            },
            { slug: "krynychansky", title: "Криничанский район", parent: "kamiansky" },
            { slug: "piatykhatky", title: "Пятихатский район", parent: "kamiansky" },
            { slug: "zhovti-vody", title: "Желтые Воды", parent: "kamiansky" },
            { slug: "krivorizky", title: "Криворожский район" },
            { slug: "apostolivsky", title: "Апостоловский район", parent: "krivorizky" },
            { slug: "sofiyivsky", title: "Софиевский район", parent: "krivorizky" },
            { slug: "shyrokivsky", title: "Широковский район", parent: "krivorizky" },
            { slug: "nikopolsky", title: "Никопольский район" },
            { slug: "marganets", title: "Марганец", parent: "nikopolsky" },
            { slug: "pokrovsk", title: "Покровск", parent: "nikopolsky" },
            { slug: "tomakivsky", title: "Томаковский район", parent: "nikopolsky" },
            { slug: "novomoskovsky", title: "Новомосковский район" },
            { slug: "magdalinivsky", title: "Магдалиновский район", parent: "novomoskovsky" },
            { slug: "pereshchepyne", title: "Перещепино", parent: "novomoskovsky" },
            { slug: "pavlogradsky", title: "Павлоградский район" },
            { slug: "ternivka", title: "Терновка", parent: "pavlogradsky" },
            { slug: "yuriivsky", title: "Юрьевский район", parent: "pavlogradsky" },
            { slug: "sinyelnikivsky", title: "Синельниковский район" },
            { slug: "vasylkivsky", title: "Васильковский район", parent: "sinyelnikivsky" },
            { slug: "pershotravensk", title: "Першотравенск", parent: "sinyelnikivsky" },
            {
                slug: "petropavlivsky",
                title: "Петропавловский район",
                parent: "sinyelnikivsky",
            },
            { slug: "pokrovsky", title: "Покровский район", parent: "sinyelnikivsky" },
        ],
    },
    {
        thumbnail: "/images/regions/dn.jpg",
        title: "Донецк",
        slug: "donetsk",
        mapId: "donetsk",
        subtitle: "",
        description:
            "Растениеводство в Донецкой области является наиболее значимой отраслью сельского хозяйства благодаря большому количеству черноземов. Основными направлениями в растениеводстве являются выращивание подсолнечника и зерновых, овощных и плодово-ягодных культур. В животноводстве преобладает мясо-молочное направление, но выращивание свиней, птицы и овец также не редкость. Развитие животноводства в области обусловлено органическим (экологически чистым) производством продукции и внедрением прогрессивных методов ведения и развития хозяйства.",
        oblast: "Донецкая область",
        locations: [
            { slug: "bakhmutske", title: "Бахмутский район" },
            { slug: "volnovaske", title: "Волновахский район" },
            {
                slug: "velikonovosilkivske",
                title: "Великоновосельковский район",
                parent: "bakhmutske",
            },
            { slug: "horlivske", title: "Горловский район" },
            { slug: "shakhtarske", title: "Шахтерский район", parent: "horlivske" },
            { slug: "debaltsieve", title: "Дебальцево", parent: "horlivske" },
            { slug: "yenakiieve", title: "Енакиево", parent: "horlivske" },
            { slug: "snizhne", title: "Снежное", parent: "horlivske" },
            { slug: "donetske", title: "Донецкий район" },
            { slug: "amvrosiivske", title: "Амвросиевский район", parent: "donetske" },
            { slug: "ilovaisk", title: "Иловайск", parent: "donetske" },
            { slug: "makiiivka", title: "Макеевка", parent: "donetske" },
            { slug: "khartsyzk", title: "Харцызск", parent: "donetske" },
            { slug: "yasinuvatske", title: "Ясиноватский район", parent: "donetske" },
            { slug: "kalmiuske", title: "Кальмиусский район" },
            { slug: "boykivske", title: "Бойковский район", parent: "kalmiuske" },
            { slug: "novoazovske", title: "Новоазовский район", parent: "kalmiuske" },
            { slug: "starobeshivske", title: "Старобешевский район", parent: "kalmiuske" },
            { slug: "dokuchayivske", title: "Докучаевск", parent: "kalmiuske" },
            { slug: "kramatorske", title: "Краматорский район" },
            { slug: "druzhkivka", title: "Дружковка", parent: "kramatorske" },
            { slug: "kostyantynivske", title: "Константиновский район", parent: "kramatorske" },
            { slug: "lymanske", title: "Лиманский район", parent: "kramatorske" },
            { slug: "oleksandrivske", title: "Александровский район", parent: "kramatorske" },
            { slug: "slovyanske", title: "Славянский район", parent: "kramatorske" },
            { slug: "mariupolske", title: "Мариупольский район" },
            { slug: "manguske", title: "Мангушский район", parent: "mariupolske" },
            { slug: "nikolske", title: "Никольский район", parent: "mariupolske" },
            { slug: "pokrovske", title: "Покровский район" },
            { slug: "avdiivka", title: "Авдеевка", parent: "pokrovske" },
            { slug: "dobropilsky", title: "Добропольский район", parent: "pokrovske" },
            { slug: "kurakhove", title: "Курахово", parent: "pokrovske" },
            { slug: "maryinka", title: "Марьинка", parent: "pokrovske" },
        ],
    },
    {
        thumbnail: "/images/regions/zh.jpg",
        title: "Житомир",
        slug: "zhytomyr",
        mapId: "zhytomyr",
        subtitle: "",
        description:
            "Аграрный потенциал Житомирской области представлен прежде всего растениеводством. Основным продуктом являются зерновые культуры (выращивание озимой пшеницы, овса, ярового ячменя), а также выращивание картофеля. Также выращиваются зернобобовые, сахарные свеклы, лен, цикорий и хмель. Первое место в Украине по использованию лесных ресурсов принадлежит Житомирской области. Около 30% территории занимают лесные массивы. Преобладают в основном хвойные породы (около 60%). На твердолистные и мягколистные породы приходится около 20%. Большая часть продукции экспортируется за пределы области.",
        oblast: "Житомирская область",
        locations: [
            { slug: "berdychivsky", title: "Бердичевский район" },
            { slug: "andrushivsky", title: "Андрушевский район", parent: "berdychivsky" },
            { slug: "ruzhynsky", title: "Ружинский район", parent: "berdychivsky" },
            { slug: "zhytomyrsky", title: "Житомирский район" },
            { slug: "brusylivsky", title: "Брусиловский район", parent: "zhytomyrsky" },
            { slug: "korostyshivsky", title: "Коростышевский район", parent: "zhytomyrsky" },
            { slug: "liubarsky", title: "Любарский район", parent: "zhytomyrsky" },
            { slug: "popilniansky", title: "Попильнянский район", parent: "zhytomyrsky" },
            { slug: "pulynsky", title: "Пулинский район", parent: "zhytomyrsky" },
            { slug: "radomyshlsky", title: "Радомышльский район", parent: "zhytomyrsky" },
            { slug: "romanivsky", title: "Романовский район", parent: "zhytomyrsky" },
            { slug: "khoroshivsky", title: "Хорошевский район", parent: "zhytomyrsky" },
            { slug: "chernyakhivsky", title: "Черняховский район", parent: "zhytomyrsky" },
            { slug: "chudnivsky", title: "Чудновский район", parent: "zhytomyrsky" },
            { slug: "korostensky", title: "Коростенский район" },
            { slug: "luhynsky", title: "Лугинский район", parent: "korostensky" },
            { slug: "malynsky", title: "Малинский район", parent: "korostensky" },
            { slug: "narodytsky", title: "Народицкий район", parent: "korostensky" },
            { slug: "ovrutsky", title: "Овруцкий район", parent: "korostensky" },
            { slug: "olevsky", title: "Олевский район", parent: "korostensky" },
            { slug: "novohrad-volynsky", title: "Новоград-Волынский район" },
            { slug: "baranivsky", title: "Барановский район", parent: "novohrad-volynsky" },
            { slug: "yemilchynsky", title: "Емильчинский район", parent: "novohrad-volynsky" },
            { slug: "horodnytsya", title: "Городница", parent: "novohrad-volynsky" },
            { slug: "dovbyske", title: "Довбыш", parent: "novohrad-volynsky" },
        ],
    },
    {
        thumbnail: "/images/regions/zk.jpg",
        title: "Закарпатье",
        slug: "zakarpattya",
        mapId: "zakarpattia",
        subtitle: "",
        description:
            "Аграрии Закарпатской области, несмотря на рельеф территории, имеют возможность заниматься не только растениеводством и животноводством, но и пчеловодством. А виноград в промышленных масштабах здесь начали выращивать еще в III веке н.э. Мясо-молочное скотоводство, свиноводство, овцеводство и птицеводство – вот направления деятельности области в животноводстве. Растениеводство представляют: виноград, картофель, ранние овощи, кормовая свекла, подсолнух, кукуруза, рожь, лен, овес, а также травы, фрукты и табак. В области хорошо развит лесопромышленный комплекс – запасы древесины в несколько раз превышают средний показатель по Украине. Это дает возможность заниматься лесозаготовками и изготовлением изделий из древесины (мебель, фанера, древесно-стружечные плиты и пиломатериалы, а также продукция лесохимии).",
        oblast: "Закарпатская область",
        locations: [
            { slug: "berehivsky", title: "Береговский район" },
            { slug: "vinohradivsky", title: "Виноградовский район", parent: "berehivsky" },
            { slug: "mukachivsky", title: "Мукачевский район" },
            { slug: "volovetsky", title: "Воловецкий район", parent: "mukachivsky" },
            { slug: "svaliavsky", title: "Свалявский район", parent: "mukachivsky" },
            { slug: "rakhivsky", title: "Раховский район" },
            { slug: "tyachivsky", title: "Тячевский район" },
            { slug: "uzhhorodsky", title: "Ужгородский район" },
            {
                slug: "velykoberizniansky",
                title: "Великоберезнянский район",
                parent: "uzhhorodsky",
            },
            { slug: "perechynsky", title: "Перечинский район", parent: "uzhhorodsky" },
            { slug: "chop", title: "Чоп", parent: "uzhhorodsky" },
            { slug: "khustsky", title: "Хустский район" },
            { slug: "irshavsky", title: "Иршавский район", parent: "khustsky" },
            { slug: "mizhhirsky", title: "Межгорский район", parent: "khustsky" },
        ],
    },
    {
        thumbnail: "/images/regions/zp.jpg",
        title: "Запорожье",
        slug: "zaporizhzhya",
        mapId: "zaporizhia",
        subtitle: "",
        description:
            "В сельском хозяйстве Запорожской области преобладает направление растениеводства. Преобладают в этом зерновые и технические культуры (подсолнечник). Благоприятные климатические условия также позволяют выращивать овощные и бахчевые культуры. В животноводстве преобладает разведение птицы и свиноводство, хотя немало внимания уделяется и выращиванию крупного рогатого скота.",
        oblast: "Запорожская область",
        locations: [
            { slug: "berdiansky", title: "Бердянский район" },
            { slug: "prymorsky", title: "Приморский район", parent: "berdiansky" },
            { slug: "chernihivsky", title: "Черниговский район", parent: "berdiansky" },
            { slug: "vasylivsky", title: "Васильевский район" },
            { slug: "enerhodar", title: "Энергодар", parent: "vasylivsky" },
            {
                slug: "kamiansko-dniprovsky",
                title: "Каменско-Днепровский район",
                parent: "vasylivsky",
            },
            { slug: "mykhailivsky", title: "Михайловский район", parent: "vasylivsky" },
            { slug: "zaporizky", title: "Запорожский район" },
            { slug: "vilniansky", title: "Вольнянский район", parent: "zaporizky" },
            { slug: "novomykolaivsky", title: "Новомиколаевский район", parent: "zaporizky" },
            { slug: "melitopolsky", title: "Мелитопольский район" },
            { slug: "veselivsky", title: "Веселовский район", parent: "melitopolsky" },
            { slug: "priazovsky", title: "Приазовский район", parent: "melitopolsky" },
            { slug: "iakymivsky", title: "Якимовский район", parent: "melitopolsky" },
            { slug: "pereiaslavsky", title: "Приазовский район", parent: "melitopolsky" },
            { slug: "pologivsky", title: "Пологовский район" },
            { slug: "bilomatsky", title: "Бильмакский район", parent: "pologivsky" },
            { slug: "huliaypilsky", title: "Гуляйпольский район", parent: "pologivsky" },
            { slug: "orikhivsky", title: "Ореховский район", parent: "pologivsky" },
            { slug: "rozivsky", title: "Розовский район", parent: "pologivsky" },
            { slug: "tokmatsky", title: "Токмакский район", parent: "pologivsky" },
        ],
    },
    {
        thumbnail: "/images/regions/if.jpg",
        title: "Ивано-Франковск",
        slug: "ivano-frankivsk",
        mapId: "ivano-frankivsk",
        subtitle: "",
        description:
            "В структуре сельскохозяйственного производства Ивано-Франковской области преобладает мясо-молочное направление животноводства. В растениеводстве - садоводство и выращивание ягод, винограда и хмеля развито слабо. Преобладают зерновые культуры, выращивание льна-долгунца и сахарных свекл.",
        oblast: "Ивано-Франковская область",
        locations: [
            { slug: "verkhovynsky", title: "Верховинский район" },
            { slug: "ivano-frankivsky", title: "Ивано-Франковский район" },
            {
                slug: "bohorodchansky",
                title: "Богородчанский район",
                parent: "ivano-frankivsky",
            },
            { slug: "halytsky", title: "Галицкий район", parent: "ivano-frankivsky" },
            { slug: "rohatynsky", title: "Рогатинский район", parent: "ivano-frankivsky" },
            { slug: "tysmenytsky", title: "Тысменицкий район", parent: "ivano-frankivsky" },
            { slug: "tlumatsky", title: "Тлумацкий район", parent: "ivano-frankivsky" },
            { slug: "kalusky", title: "Калуский район" },
            { slug: "dolynsky", title: "Долинский район", parent: "kalusky" },
            { slug: "rozhnyativsky", title: "Рожнятовский район", parent: "kalusky" },
            { slug: "kolomyisky", title: "Коломыйский район" },
            { slug: "horodenkivsky", title: "Городенковский район", parent: "kolomyisky" },
            { slug: "sniatynsky", title: "Снятынский район", parent: "kolomyisky" },
            { slug: "kosivsky", title: "Косовский район" },
            { slug: "nadvirnyansky", title: "Надворнянский район" },
            { slug: "vorokhta", title: "Ворохта", parent: "nadvirnyansky" },
            { slug: "delyatyn", title: "Делятин", parent: "nadvirnyansky" },
            { slug: "yaremche", title: "Яремче", parent: "nadvirnyansky" },
        ],
    },
    {
        thumbnail: "/images/regions/ky.jpg",
        title: "Киев",
        slug: "kyiv",
        mapId: "kyiv",
        subtitle: "",
        description:
            "Сельское хозяйство в Киевской области, благодаря своему географическому положению, характеризуется наивысшим, чем в других областях, уровнем развития. А территориально-климатические факторы и природные характеристики дают возможность работать по разнообразным направлениям. Но основная специализация акцентируется на выращивании свеклы, зерновых культур. Мясо-молочное направление и птицеводство являются основными направлениями в животноводстве области.",
        oblast: "Киевская область",
        locations: [
            { slug: "bilotserkivsky", title: "Белоцерковский район" },
            { slug: "volodarsky", title: "Володарский район", parent: "bilotserkivsky" },
            { slug: "rokytnyansky", title: "Ракитнянский район", parent: "bilotserkivsky" },
            { slug: "skvyrsky", title: "Сквирский район", parent: "bilotserkivsky" },
            { slug: "stavishchensky", title: "Ставищенский район", parent: "bilotserkivsky" },
            { slug: "tarashchansky", title: "Таращанский район", parent: "bilotserkivsky" },
            { slug: "boryspilsky", title: "Бориспольский район" },
            { slug: "peryaslavsky", title: "Переяславский район", parent: "boryspilsky" },
            { slug: "yahotynsky", title: "Яготинский район", parent: "boryspilsky" },
            { slug: "brovarsky", title: "Броварский район" },
            { slug: "baryshivsky", title: "Барышевский район", parent: "brovarsky" },
            { slug: "zghurivsky", title: "Згуровский район", parent: "brovarsky" },
            { slug: "buchansky", title: "Бучанский район" },
            { slug: "borodyansky", title: "Бородянский район", parent: "buchansky" },
            { slug: "vyshneve", title: "Вышневое", parent: "buchansky" },
            { slug: "irpinsky", title: "Ирпенский район", parent: "buchansky" },
            { slug: "makarivsky", title: "Макаровский район", parent: "buchansky" },
            { slug: "vyshhorodsky", title: "Вышгородский район" },
            { slug: "ivankivsky", title: "Иванковский район", parent: "vyshhorodsky" },
            { slug: "polissky", title: "Полесский район", parent: "vyshhorodsky" },
            { slug: "obukhivsky", title: "Обуховский район" },
            { slug: "bohuslavsky", title: "Богуславский район", parent: "obukhivsky" },
            { slug: "vasylkivsky", title: "Васильковский район", parent: "obukhivsky" },
            { slug: "kaharlytsky", title: "Кагарлыкский район", parent: "obukhivsky" },
            { slug: "myronivsky", title: "Мироновский район", parent: "obukhivsky" },
            { slug: "rzhyshchivsky", title: "Ржищевский район", parent: "obukhivsky" },
            { slug: "fastivsky", title: "Фастовский район" },
            { slug: "boiarka", title: "Боярка", parent: "fastivsky" },
            { slug: "kalynivsky", title: "Калиновка", parent: "fastivsky" },
            { slug: "hlevakha", title: "Глеваха", parent: "fastivsky" }
        ]
    },
    {
        thumbnail: "/images/regions/kr.jpg",
        title: "Кропивницкий",
        slug: "kropyvnytskyi",
        mapId: "kirovohrad",
        subtitle: "",
        description: "Сельскохозяйственное производство в экономике Кировоградской области, благодаря природным черноземам и климатическим условиям, занимает ведущее положение. Основные направления в растениеводстве - выращивание ячменя, озимой пшеницы, зернобобовых, гречихи и проса, а также кукурузы на зерно. Технические культуры представлены в основном выращиванием сахарных свекл и подсолнечника. Также выращивают сою. Активно развивается садоводство. Здесь преобладают направления выращивания вишен, груш, яблок, слив. Развивается выращивание ягодных культур. В животноводстве активно развивается птицеводство. Выращивают свиней, крупного рогатого скота и овец. Существуют предприятия, занимающиеся разведением племенных лошадей.",
        oblast: "Кировоградская область",
        locations: [
            { slug: "holovanivsky", title: "Голованевский район" },
            { slug: "blahovishchensky", title: "Благовещенский район", parent: "holovanivsky" },
            { slug: "vilshansky", title: "Ольшанский район", parent: "holovanivsky" },
            { slug: "haivoronsky", title: "Гайворонский район", parent: "holovanivsky" },
            { slug: "novoarkhanhelsky", title: "Новоархангельский район", parent: "holovanivsky" },
            { slug: "kropyvnytskyi", title: "Кропивницкий район" },
            { slug: "bobrynetsky", title: "Бобринецкий район", parent: "kropyvnytskyi" },
            { slug: "dolynsky", title: "Долинский район", parent: "kropyvnytskyi" },
            { slug: "znamiansky", title: "Знаменский район", parent: "kropyvnytskyi" },
            { slug: "kompaniivsky", title: "Компанеевский район", parent: "kropyvnytskyi" },
            { slug: "novhorodkivsky", title: "Новгородковский район", parent: "kropyvnytskyi",},
            { slug: "oleksandrivskyi", title: "Александрийский район", parent: "kropyvnytskyi" },
            { slug: "novoukrainsky", title: "Александрия" },
            { slug: "dobrovelychkivsky", title: "Новоукраинский район", parent: "novoukrainsky" },
            { slug: "malovyskivsky", title: "Добровеличковский район", parent: "novoukrainsky" },
            { slug: "novomyrhorodsky", title: "Маловискевский район", parent: "novoukrainsky" },
            { slug: "oleksandriia", title: "Новомиргородский район" },
            { slug: "onufriivsky", title: "Онуфриевский район", parent: "oleksandriia" },
            { slug: "petrivsky", title: "Петровский район", parent: "oleksandriia" },
            { slug: "svitlovodsky", title: "Светловодский район", parent: "oleksandriia" },
        ],
    },
    {
        thumbnail: "/images/regions/lg.jpg",
        title: "Луганск",
        slug: "lugansk",
        mapId: "luhansk",
        subtitle: "",
        description: "Основная специализация сельского хозяйства Луганской области в растениеводстве заключается в выращивании, в основном, кукурузы, озимой пшеницы и подсолнечника. Развито овощеводство. В животноводстве специализируется на птицеводстве и мясо-молочном скотоводстве. Развивается овцеводство.",
        oblast: "Луганская область",
        locations: [
            { slug: "alchevskiy", title: "Алчевский район" },
            { slug: "kadiivka", title: "Кадиевка", parent: "alchevskiy" },
            { slug: "zimogirivskiy", title: "Зимогорьевский", parent: "alchevskiy" },
            { slug: "dovzhanskiy", title: "Довжанский район" },
            { slug: "luganskiy", title: "Луганский район" },
            { slug: "lutugino", title: "Лутугино", parent: "luganskiy" },
            { slug: "molodogvardiysk", title: "Молодогвардейск", parent: "luganskiy" },
            { slug: "rovenkovskiy", title: "Ровеньковский район" },
            { slug: "antratsit", title: "Антрацит", parent: "rovenkovskiy" },
            { slug: "rovenki", title: "Ровеньки", parent: "rovenkovskiy" },
            { slug: "khrustalniy", title: "Хрустальный", parent: "rovenkovskiy" },
            { slug: "svativskiy", title: "Сватовский район" },
            { slug: "bilokurakinskiy", title: "Белокуракинский район", parent: "svativskiy" },
            { slug: "severodonetsk", title: "Северодонецкий район" },
            { slug: "gorskoe", title: "Горское", parent: "severodonetsk" },
            { slug: "kreminskiy", title: "Кременский район", parent: "severodonetsk" },
            { slug: "lisichansk", title: "Лисичанск", parent: "severodonetsk" },
            { slug: "popasnyanskiy", title: "Попаснянский район", parent: "severodonetsk" },
            { slug: "rubizhne", title: "Рубежное", parent: "severodonetsk" },
            { slug: "starobilskiy", title: "Старобельский район" },
            { slug: "bilovodskiy", title: "Беловодский район", parent: "starobilskiy" },
            { slug: "markivskiy", title: "Марковский район", parent: "starobilskiy" },
            { slug: "milovskiy", title: "Миловский район", parent: "starobilskiy" },
            { slug: "novopskovskiy", title: "Новопсковский район", parent: "starobilskiy" },
            { slug: "shchastinskiy", title: "Щастинский район" },
            { slug: "stanichno-luganskiy", title: "Станично-Луганский район", parent: "shchastinskiy" },
            { slug: "shchastie", title: "Щастя", parent: "shchastinskiy" },
            { slug: "novoaydar", title: "Новоайдар", parent: "shchastinskiy" }
        ]
    },
    {
        thumbnail: "/images/regions/lv.jpg",
        title: "Львов",
        slug: "lviv",
        mapId: "lviv",
        subtitle: "",
        description: "Основной акцент в сельском хозяйстве Львовской области приходится на животноводство мясо-молочного направления (выращивание крупного рогатого скота, свиноводство). На долю животноводства приходится около 60% валовой сельхозпродукции области. Также присутствуют: птицеводство, овцеводство, прудовое разведение рыбы и пчеловодство. Растениеводство в основном специализируется на выращивании зерновых культур (озимая пшеница – около 20% посевных площадей, яровой ячмень). Выращивается и технические культуры (сахарная свекла, лен-долгунец). Увеличиваются площади под выращивание картофеля и овощей.",
        oblast: "Львовская область",
        locations: [
            { slug: "drohobychskyi", title: "Дрогобычский район" },
            { slug: "borislav", title: "Борислав", parent: "drohobychskyi" },
            { slug: "skhidnytsia", title: "Схидница", parent: "drohobychskyi" },
            { slug: "truskavets", title: "Трускавец", parent: "drohobychskyi" },
            { slug: "zolochivskyi", title: "Золочевский район" },
            { slug: "brody", title: "Броды", parent: "zolochivskyi" },
            { slug: "busk", title: "Буск", parent: "zolochivskyi" },
            { slug: "pidkamin", title: "Подкамень", parent: "zolochivskyi" },
            { slug: "pomoriany", title: "Поморяны", parent: "zolochivskyi" },
            { slug: "lvivskyi", title: "Львовский район" },
            { slug: "bibirka", title: "Бибрка", parent: "lvivskyi" },
            { slug: "horodok", title: "Городок", parent: "lvivskyi" },
            { slug: "zhovkva", title: "Жолковский район", parent: "lvivskyi" },
            { slug: "kamianka-buzka", title: "Каменка-Бугская", parent: "lvivskyi" },
            { slug: "peremyshliany", title: "Перемышляны", parent: "lvivskyi" },
            { slug: "pustomyty", title: "Пустомыты", parent: "lvivskyi" },
            { slug: "rava-ruska", title: "Рава-Русская", parent: "lvivskyi" },
            { slug: "sambirskyi", title: "Самборский район" },
            { slug: "dobromyl", title: "Добромиль", parent: "sambirskyi" },
            { slug: "starosambir", title: "Старый Самбор", parent: "sambirskyi" },
            { slug: "khyriv", title: "Хыров", parent: "sambirskyi" },
            { slug: "stryiskyi", title: "Стрыйский район" },
            { slug: "zhidachiv", title: "Жидачов", parent: "stryiskyi" },
            { slug: "mykolaiv", title: "Николаев", parent: "stryiskyi" },
            { slug: "morshyn", title: "Моршин", parent: "stryiskyi" },
            { slug: "skole", title: "Сколе", parent: "stryiskyi" },
            { slug: "slavske", title: "Славское", parent: "stryiskyi" },
            { slug: "khodoriv", title: "Ходоров", parent: "stryiskyi" },
            { slug: "chervonohradskyi", title: "Червоноградский район" },
            { slug: "belz", title: "Белз", parent: "chervonohradskyi" },
            { slug: "radekhiv", title: "Радехов", parent: "chervonohradskyi" },
            { slug: "sokal", title: "Сокаль", parent: "chervonohradskyi" },
            { slug: "yavorivskyi", title: "Яворовский район" },
            { slug: "mostyska", title: "Мостиска", parent: "yavorivskyi" },
            { slug: "novoyavorivsk", title: "Новояворовск", parent: "yavorivskyi" },
            { slug: "sudova-vyshnia", title: "Судовая Вишня", parent: "yavorivskyi" },
            { slug: "shehyni", title: "Шегини", parent: "yavorivskyi" }
        ]
    },
    {
        thumbnail: "/images/regions/mk.jpg",
        title: "Николаев",
        slug: "mykolaiv",
        mapId: "mykolaiv",
        subtitle: "",
        description: "Благоприятные климатические условия в Николаевской области позволяют активно развивать в сельском хозяйстве направление растениеводства. Основными культурами здесь являются зерновые (яровой ячмень, озимая пшеница и кукуруза), технические (сахарные свеклы, подсолнечник) и бахчевые культуры. Хорошо развиты садоводство и виноградарство. Животноводство представлено мясо-молочным направлением. Развивается птицеводство.",
        oblast: "Николаевская область",
        locations: [
            { slug: "bashtanskyi", title: "Баштанский район" },
            { slug: "berezneguvatskyi", title: "Березнегуватский район", parent: "bashtanskyi" },
            { slug: "novobuzkyi", title: "Новобугский район", parent: "bashtanskyi" },
            { slug: "snihurivskyi", title: "Снигиревский район", parent: "bashtanskyi" },
            { slug: "voznesenskyi", title: "Вознесенский район" },
            { slug: "bratskyi", title: "Братский район", parent: "voznesenskyi" },
            { slug: "veselynivskyi", title: "Веселиновский район", parent: "voznesenskyi" },
            { slug: "domanivskyi", title: "Доманевский район", parent: "voznesenskyi" },
            { slug: "yelanetskyi", title: "Еланецкий район", parent: "voznesenskyi" },
            { slug: "yuzhnyoukrainsk", title: "Южноукраинск", parent: "voznesenskyi" },
            { slug: "mykolaivskyi", title: "Николаевский район" },
            { slug: "berezhanskyi", title: "Березанский район", parent: "mykolaivskyi" },
            { slug: "novoodeskyi", title: "Новоодесский район", parent: "mykolaivskyi" },
            { slug: "ochakivskyi", title: "Очаковский район", parent: "mykolaivskyi" },
            { slug: "perwomayskyi", title: "Первомайский район" },
            { slug: "arbuzynskyi", title: "Арбузинский район", parent: "perwomayskyi" },
            { slug: "vradiyivskyi", title: "Врадиевский район", parent: "perwomayskyi" },
            { slug: "kryvoozerskyi", title: "Кривоозерский район", parent: "perwomayskyi" }
        ]
    },
    {
        thumbnail: "/images/regions/od.jpg",
        title: "Одесса",
        slug: "odesa",
        mapId: "odessa",
        subtitle: "",
        description: "Практически все продуктивные угодья в Одесской области закреплены за сельхозпроизводителями. В растениеводстве основными здесь являются зерновые культуры. Также выращивается подсолнечник и виноград. Животноводство в основном представлено выращиванием птицы и свиноводством.",
        oblast: "Одесская область",
        locations: [
            { slug: "berezivskyi", title: "Березовский район" },
            { slug: "mykolaivskyi", title: "Николаевский район", parent: "berezivskyi" },
            { slug: "shyriaiivskyi", title: "Ширяевский район", parent: "berezivskyi" },
            { slug: "bilhorod-dnistrovskyi", title: "Белгород-Днестровский район" },
            { slug: "saratovskyi", title: "Саратский район", parent: "bilhorod-dnistrovskyi" },
            { slug: "tatarbunarskyi", title: "Татарбунарский район", parent: "bilhorod-dnistrovskyi"},
            { slug: "bolhradskyi", title: "Болградский район" },
            { slug: "artsyzkyi", title: "Арцизский район", parent: "bolhradskyi" },
            { slug: "tarutynskyi", title: "Тарутинский район", parent: "bolhradskyi" },
            { slug: "izmailskyi", title: "Измаильский район" },
            { slug: "vylkove", title: "Вилково", parent: "izmailskyi" },
            { slug: "kiliiskyi", title: "Килийский район", parent: "izmailskyi" },
            { slug: "reniyskyi", title: "Ренийский район", parent: "izmailskyi" },
            { slug: "odeskyi", title: "Одесский район" },
            { slug: "biliaivskyi", title: "Беляевский район", parent: "odeskyi" },
            { slug: "ovidiopolskyi", title: "Овидиопольский район", parent: "odeskyi" },
            { slug: "chornomorskyi", title: "Черноморский район", parent: "odeskyi" },
            { slug: "yuzhne", title: "Южное", parent: "odeskyi" },
            { slug: "podilskyi", title: "Подольский район" },
            { slug: "ananiivskyi", title: "Ананьевский район", parent: "podilskyi" },
            { slug: "baltskyi", title: "Балтский район", parent: "podilskyi" },
            { slug: "kodymskyi", title: "Кодымский район", parent: "podilskyi" },
            { slug: "liubashivskyi", title: "Любашевский район", parent: "podilskyi" },
            { slug: "oknianskyi", title: "Окнянский район", parent: "podilskyi" },
            { slug: "savranskyi", title: "Савранский район", parent: "podilskyi" },
            { slug: "rozdilnianskyi", title: "Раздельнянский район" },
            { slug: "velykomikhaylivskyi", title: "Великомихайловский район", parent: "rozdilnianskyi" },
            { slug: "zakhariivskyi", title: "Захарьевский район", parent: "rozdilnianskyi" },
            { slug: "lymanskyi", title: "Лиманский район", parent: "rozdilnianskyi" }
        ]
    },
    {
        thumbnail: "/images/regions/pl.jpg",
        title: "Полтава",
        slug: "poltava",
        mapId: "poltava",
        subtitle: "",
        description: "Производство молока, зерна и технических культур характеризуют сельское хозяйство Полтавской области, которое составляет основу агропромышленного комплекса. Черноземы - наиболее распространенные почвы, занимающие около 90% площади, а традиционной для Полтавщины отраслью является животноводство. Здесь расположена одна из крупнейших в Украине племенных баз. Успешно действуют племенные хозяйства, занимающиеся разведением КРС и свиноводством. В Миргородском районе расположен Дубровский конный завод, известный своими рекордсменами далеко за пределами Украины.",
        oblast: "Полтавская область",
        locations: [
            { slug: "poltava", title: "Полтавский район" },
            { slug: "dikanka", title: "Диканка", parent: "poltava" },
            { slug: "zinkiv", title: "Зеньковский район", parent: "poltava" },
            { slug: "karlivka", title: "Карловка", parent: "poltava" },
            { slug: "kobelyaki", title: "Кобеляки", parent: "poltava" },
            { slug: "kotelva", title: "Котельва", parent: "poltava" },
            { slug: "novi-sanzhary", title: "Новые Санжары", parent: "poltava" },
            { slug: "opishnya", title: "Опошня", parent: "poltava" },
            { slug: "reshetylivka", title: "Решетиловка", parent: "poltava" },
            { slug: "kremenchuk", title: "Кременчугский район" },
            { slug: "globino", title: "Глобино", parent: "kremenchuk" },
            { slug: "gorishni-plavni", title: "Горишние Плавни", parent: "kremenchuk" },
            { slug: "mirgorod", title: "Миргородский район" },
            { slug: "gadyach", title: "Гадяч", parent: "mirgorod" },
            { slug: "gogolivske", title: "Гоголевское", parent: "mirgorod" },
            { slug: "lokhvytsia", title: "Лохвица", parent: "mirgorod" },
            { slug: "romodanivske", title: "Ромодановское", parent: "mirgorod" },
            { slug: "shishaki", title: "Шишаки", parent: "mirgorod" },
            { slug: "lubny", title: "Лубенский район" },
            { slug: "hrebinka", title: "Гребенка", parent: "lubny" },
            { slug: "pyryatyn", title: "Пирятин", parent: "lubny" },
            { slug: "khorol", title: "Хорол", parent: "lubny" },
            { slug: "chornukhine", title: "Чернухино", parent: "lubny" }
        ]
    },
    {
        thumbnail: "/images/regions/rv.jpg",
        title: "Ровно",
        slug: "rivne",
        mapId: "rivne",
        subtitle: "",
        description: "Целый ряд мероприятий, направленных на поддержание и повышение производительности в сельском хозяйстве, проводят в Ровенской области. В южных районах высокий уровень эрозии почв, заболоченность и переувлажненность почвы встречается по всей территории. Присутствует ряд факторов, вызванных аварией на ЧАЭС. Основными направлениями деятельности здесь можно назвать выращивание картофеля и сахарных свекл, зерновых культур и льна-долгунца (растениеводство) и мясо-молочное направление (животноводство).",
        oblast: "Ровенская область",
        locations: [
            { slug: "varasskiy", title: "Варашский район" },
            { slug: "vladimiretskiy", title: "Владимирецкий район", parent: "varasskiy" },
            { slug: "zarichnenskiy", title: "Заречненский район", parent: "varasskiy" },
            { slug: "dubenskiy", title: "Дубенский район" },
            { slug: "demidovskiy", title: "Демидовский район", parent: "dubenskiy" },
            { slug: "mlinovskiy", title: "Млиновский район", parent: "dubenskiy" },
            { slug: "radivilovskiy", title: "Радивиловский район", parent: "dubenskiy" },
            { slug: "rivenskiy", title: "Ровенский район" },
            { slug: "bereznovskiy", title: "Березновский район", parent: "rivenskiy" },
            { slug: "goshchanskiy", title: "Гощанский район", parent: "rivenskiy" },
            { slug: "zdolbunovskiy", title: "Здолбуновский район", parent: "rivenskiy" },
            { slug: "klevan", title: "Клевань", parent: "rivenskiy" },
            { slug: "koretskiy", title: "Корецкий район", parent: "rivenskiy" },
            { slug: "kostopilskiy", title: "Костопольский район", parent: "rivenskiy" },
            { slug: "ostrogskiy", title: "Острожский район", parent: "rivenskiy" },
            { slug: "sarnenskiy", title: "Сарненский район" },
            { slug: "dubrovitskiy", title: "Дубровицкий район", parent: "sarnenskiy" },
            { slug: "rokitnovskiy", title: "Рокитновский район", parent: "sarnenskiy" },
            { slug: "klesiv", title: "Клесов", parent: "sarnenskiy" }
        ]
    },
    {
        thumbnail: "/images/regions/sm.jpg",
        title: "Сумы",
        slug: "sumy",
        mapId: "sumy",
        subtitle: "",
        description:
            "Одной из ведущих отраслей экономики Сумского региона является аграрный сектор. Сельское хозяйство области специализируется на зерновых и технических культурах в растениеводстве и на производстве мяса КРС и свиней, а также молока в животноводстве. Пашня составляет более 1 млн. га, а общая площадь сельхозугодий области свыше 1.5 млн. гектаров.",
        oblast: "Сумская область",
        locations: [
            { slug: "konotopskyi", title: "Конотопский район" },
            { slug: "burynskyi", title: "Буринский район", parent: "konotopskyi" },
            { slug: "krolevetskyi", title: "Кролевецкий район", parent: "konotopskyi" },
            { slug: "putivlskyi", title: "Путивльский район", parent: "konotopskyi" },
            { slug: "okhtyrskyi", title: "Ахтырский район" },
            {
                slug: "velykopysarivskyi",
                title: "Великописаревский район",
                parent: "okhtyrskyi",
            },
            { slug: "trostyanetskyi", title: "Тростянецкий район", parent: "okhtyrskyi" },
            { slug: "romenskyi", title: "Роменский район" },
            { slug: "lypovodynskyi", title: "Липоводолинский район", parent: "romenskyi" },
            { slug: "nedryhaylivskyi", title: "Недригайловский район", parent: "romenskyi" },
            { slug: "sumskyi", title: "Сумский район" },
            { slug: "bilopilskyi", title: "Белопольский район", parent: "sumskyi" },
            { slug: "krasnopilskyi", title: "Краснопольский район", parent: "sumskyi" },
            { slug: "lebedynskyi", title: "Лебединский район", parent: "sumskyi" },
            { slug: "shostkinskyi", title: "Шосткинский район" },
            { slug: "hlukhivskyi", title: "Глуховский район", parent: "shostkinskyi" },
            {
                slug: "seredynobudskyi",
                title: "Середино-Будский район",
                parent: "shostkinskyi",
            },
            { slug: "yampilskyi", title: "Ямпольский район", parent: "shostkinskyi" }
        ]
    },
    {
        thumbnail: "/images/regions/tr.jpg",
        title: "Тернополь",
        slug: "ternopil",
        mapId: "ternopil",
        subtitle: "",
        description: "Тернопольская область является развитым промышленным и сельскохозяйственным регионом. Более 50% валовой продукции в сельском хозяйстве приходится на растениеводство. Основное внимание уделяется выращиванию зерновых культур. Большая часть в производстве технических культур занимает сахарная свекла. Основой животноводческой отрасли является мясо-молочное направление. Ведущее направление в Украине Тернопольская область занимает в производстве березового сока, лекарственных трав, ягод и дикорастущих плодов.",
        oblast: "Тернопольская область",
        locations: [
            { slug: "kremenetskyy", title: "Кременецкий район" },
            { slug: "lanovetskyy", title: "Лановецкий район", parent: "kremenetskyy" },
            { slug: "pochaiv", title: "город Почаев", parent: "kremenetskyy" },
            { slug: "shumskyy", title: "Шумский район", parent: "kremenetskyy" },
            { slug: "ternopilskyy", title: "Тернопольский район" },
            { slug: "berezhanskyy", title: "Бережанский район", parent: "ternopilskyy" },
            { slug: "zbarazkyy", title: "Збаражский район", parent: "ternopilskyy" },
            { slug: "zborivskyy", title: "Зборовский район", parent: "ternopilskyy" },
            { slug: "pidvolochyskyy", title: "Подволочиский район", parent: "ternopilskyy" },
            { slug: "pidhayetskyy", title: "Подгаецкий район", parent: "ternopilskyy" },
            { slug: "terebovlyanskyy", title: "Теребовлянский район", parent: "ternopilskyy" },
            { slug: "chortkivskyy", title: "Чортковский район" },
            { slug: "borschivskyy", title: "Борщевский район", parent: "chortkivskyy" },
            { slug: "buchatskyy", title: "Бучачский район", parent: "chortkivskyy" },
            { slug: "husyatynskyy", title: "Гусятинский район", parent: "chortkivskyy" },
            { slug: "zalishchytskyy", title: "Залещицкий район", parent: "chortkivskyy" },
            { slug: "monastyryskyy", title: "Монастыриский район", parent: "chortkivskyy" }
        ]
    },
    {
        thumbnail: "/images/regions/khk.jpg",
        title: "Харьков",
        slug: "kharkiv",
        mapId: "kharkiv",
        subtitle: "",
        description: "Богатые черноземами почвы и высокий уровень автоматизации и механизации сельского хозяйства - вот основные причины высокой продуктивности сельского хозяйства в Харьковской области. В растениеводстве отдают предпочтение выращиванию подсолнечника, пшеницы, рапса, ячменя, проса и сахарных свекл. В овощеводстве преобладает выращивание картофеля. В животноводстве, в равных долях, выращивают птицу, свиней и КРС.",
        oblast: "Харьковская область",
        locations: [
            { slug: "bogodukhovskiy", title: "Богодуховский район" },
            { slug: "valkovskiy", title: "Валковский район", parent: "bogodukhovskiy" },
            { slug: "zolochevskiy", title: "Золочевский район", parent: "bogodukhovskiy" },
            { slug: "kolomatskiy", title: "Коломацкий район", parent: "bogodukhovskiy" },
            { slug: "krasnokutskiy", title: "Краснокутский район", parent: "bogodukhovskiy" },
            { slug: "izyumskiy", title: "Изюмский район" },
            { slug: "balakliyskiy", title: "Балаклейский район", parent: "izyumskiy" },
            { slug: "barvinkovskiy", title: "Барвинковский район", parent: "izyumskiy" },
            { slug: "borovskiy", title: "Боровский район", parent: "izyumskiy" },
            { slug: "krasnogradskiy", title: "Красноградский район" },
            { slug: "zachepilovskiy", title: "Зачепиловский район", parent: "krasnogradskiy" },
            { slug: "kegichevskiy", title: "Кегичевский район", parent: "krasnogradskiy" },
            { slug: "sakhnovshchinskiy", title: "Сахновщинский район", parent: "krasnogradskiy" },
            { slug: "kupyanskiy", title: "Купянский район" },
            { slug: "velikoburlukskiy", title: "Великобурлукский район", parent: "kupyanskiy" },
            { slug: "dvorichanskiy", title: "Двуречанский район", parent: "kupyanskiy" },
            { slug: "shevchenkovskiy", title: "Шевченковский район", parent: "kupyanskiy" },
            { slug: "lozovskiy", title: "Лозовский район" },
            { slug: "blyznyukovskiy", title: "Близнюковский район", parent: "lozovskiy" },
            { slug: "permyakovskiy", title: "Первомайский район", parent: "lozovskiy" },
            { slug: "kharkovskiy", title: "Харьковский район" },
            { slug: "dergachovskiy", title: "Дергачевский район", parent: "kharkovskiy" },
            { slug: "lyubotinskiy", title: "Люботинский район", parent: "kharkovskiy" },
            { slug: "novovodolazhskiy", title: "Нововодолажский район", parent: "kharkovskiy" },
            { slug: "chuguevskiy", title: "Чугуевский район" },
            { slug: "vovchanskiy", title: "Волчанский район", parent: "chuguevskiy" },
            { slug: "zmiyevskiy", title: "Змиевский район", parent: "chuguevskiy" },
            { slug: "pechenizhskiy", title: "Печенежский район", parent: "chuguevskiy" }
        ]
    },
    {
        thumbnail: "/images/regions/khr.jpg",
        title: "Херсон",
        slug: "kherson",
        mapId: "kherson",
        subtitle: "",
        description: "Благоприятные климатические условия и высокая плодородность почвы объясняют большой потенциал сельского хозяйства в Херсонской области. Это объясняется благоприятными климатическими условиями и высокой плодородностью почвы. Большое внимание уделяется выращиванию подсолнечника, риса, кукурузы, озимой пшеницы, арбузов и томатов. Развито садоводство и выращивание винограда. Также в области хорошо развита перерабатывающая промышленность.",
        oblast: "Херсонская область",
        locations: [
            { slug: "berislavskiy", title: "Бериславский район" },
            { slug: "velikooleksandrovskiy", title: "Великоалександровский район", parent: "berislavskiy" },
            { slug: "visokopilskiy", title: "Высокопильский район", parent: "berislavskiy" },
            { slug: "novovorontsovskiy", title: "Нововоронцовский район", parent: "berislavskiy" },
            { slug: "genicheskiy", title: "Генический район" },
            { slug: "ivanovskiy", title: "Ивановский район", parent: "genicheskiy" },
            { slug: "nizhnosirogozskiy", title: "Нижнесирогозский район", parent: "genicheskiy" },
            { slug: "novotroitskiy", title: "Новотроицкий район", parent: "genicheskiy" },
            { slug: "kakhovskiy", title: "Каховский район" },
            { slug: "velikolepetiskiy", title: "Великолепетихский район", parent: "kakhovskiy" },
            { slug: "verkhnerogachitskiy", title: "Верхнерогачицкий район", parent: "kakhovskiy" },
            { slug: "gornostayivskiy", title: "Горностаивский район", parent: "kakhovskiy" },
            { slug: "chaplynskiy", title: "Чаплинский район", parent: "kakhovskiy" },
            { slug: "nova-kakhovka", title: "Новая Каховка", parent: "kakhovskiy" },
            { slug: "skadovskiy", title: "Скадовский район" },
            { slug: "golopristanskiy", title: "Голопристанский район", parent: "skadovskiy" },
            { slug: "kalanchatskiy", title: "Каланчакский район", parent: "skadovskiy" },
            { slug: "khersonskiy", title: "Херсонский район" },
            { slug: "bilozeretskiy", title: "Белозерский район", parent: "khersonskiy" },
            { slug: "oleshkovskiy", title: "Олешковский район", parent: "khersonskiy" }
        ]
    },
    {
        thumbnail: "/images/regions/khm.jpg",
        title: "Хмельницкий",
        slug: "khmelnytskyi",
        mapId: "khmelnytskyi",
        subtitle: "",
        description: "Большая часть сельскохозяйственной продукции Хмельницкой области приходится на растениеводство. Наибольшую площадь посевов занимает пшеница. Выращивают много озимых, а также зернобобовые, кукурузу, гречиху, просо, ячмень, рожь, овес, сахарные свеклы и другие кормовые культуры. Хорошо развито садоводство. В животноводстве главное - мясо-молочное направление, также присутствуют овцеводство, птицеводство, кролиководство, пчеловодство, разведение рыбы.",
        oblast: "Хмельницкая область",
        locations: [
            { slug: "kamyanets-podilskyy", title: "Каменец-Подольский район" },
            { slug: "dunayevetskyy", title: "Дунаевецкий район", parent: "kamyanets-podilskyy" },
            { slug: "novoushytskyy", title: "Новоушицкий район", parent: "kamyanets-podilskyy" },
            { slug: "chemerovetskyy", title: "Чемеровецкий район", parent: "kamyanets-podilskyy" },
            { slug: "khmelnytskyy", title: "Хмельницкий район" },
            { slug: "vinkovetskyy", title: "Виньковецкий район", parent: "khmelnytskyy" },
            { slug: "volochyskyy", title: "Волочиский район", parent: "khmelnytskyy" },
            { slug: "horodotskyy", title: "Городоцкий район", parent: "khmelnytskyy" },
            { slug: "derazhnyanskyy", title: "Деражнянский район", parent: "khmelnytskyy" },
            { slug: "krasylivskyy", title: "Красиловский район", parent: "khmelnytskyy" },
            { slug: "letychivskyy", title: "Летичевский район", parent: "khmelnytskyy" },
            { slug: "starokostyantynivskyy", title: "Староконстантиновский район", parent: "khmelnytskyy" },
            { slug: "starosyniavskyy", title: "Старосинявский район", parent: "khmelnytskyy" },
            { slug: "teofipolksyy", title: "Теофипольский район", parent: "khmelnytskyy" },
            { slug: "yarmolyntsiyskyy", title: "Ярмолинецкий район", parent: "khmelnytskyy" },
            { slug: "shepetivskyy", title: "Шепетовский район" },
            { slug: "bilohirskyy", title: "Белогорский район", parent: "shepetivskyy" },
            { slug: "izyaslavskyy", title: "Изяславский район", parent: "shepetivskyy" },
            { slug: "slavutskyy", title: "Славутский район", parent: "shepetivskyy" },
            { slug: "netishyn", title: "Нетешин", parent: "shepetivskyy" }
        ]
    },
    {
        thumbnail: "/images/regions/chrk.jpg",
        title: "Черкассы",
        slug: "cherkasy",
        mapId: "cherkasy",
        subtitle: "",
        description: "В Черкасской области общая площадь сельскохозяйственных угодий составляет почти 90%. Ведущие места область занимает по уровню плодородия почв. Традиционно в Черкассах в области растениеводства преобладает выращивание зерновых культур и сахарной свеклы. А животноводство представлено мясо-молочным направлением.",
        oblast: "Черкасская область",
        locations: [
            { slug: "zvenigorodskyy", title: "Звенигородский район" },
            { slug: "vatutine", title: "Ватутино", parent: "zvenigorodskyy" },
            { slug: "katerynopilskyy", title: "Катеринопольский район", parent: "zvenigorodskyy" },
            { slug: "lysianskyy", title: "Лысянский район", parent: "zvenigorodskyy" },
            { slug: "talnivskyy", title: "Тальновский район", parent: "zvenigorodskyy" },
            { slug: "shpolyanskyy", title: "Шполянский район", parent: "zvenigorodskyy" },
            { slug: "zolotonoshskyy", title: "Золотоношский район" },
            { slug: "drabivskyy", title: "Драбовский район", parent: "zolotonoshskyy" },
            { slug: "chornobayivskyy", title: "Чернобаевский район", parent: "zolotonoshskyy" },
            { slug: "umanskyy", title: "Уманский район" },
            { slug: "zhashkivskyy", title: "Жашковский район", parent: "umanskyy" },
            { slug: "mankivskyy", title: "Маньковский район", parent: "umanskyy" },
            { slug: "monastyryshchenskyy", title: "Монастырищенский район", parent: "umanskyy" },
            { slug: "khrystynivskyy", title: "Христиновский район", parent: "umanskyy" },
            { slug: "cherkaskyy", title: "Черкасский район" },
            { slug: "horodyshchenskyy", title: "Городищенский район", parent: "cherkaskyy" },
            { slug: "kamyanetskyy", title: "Каменский район", parent: "cherkaskyy" },
            { slug: "kanivskyy", title: "Каневский район", parent: "cherkaskyy" },
            { slug: "korsun-shevchenkivskyy", title: "Корсунь-Шевченковский район", parent: "cherkaskyy" },
            { slug: "smilyanskyy", title: "Смелянский район", parent: "cherkaskyy" },
            { slug: "chyhyrynskyy", title: "Чигиринский район", parent: "cherkaskyy" }
        ]
    },
    {
        thumbnail: "/images/regions/chrg.jpg",
        title: "Чернигов",
        slug: "chernihiv",
        mapId: "chernihiv",
        subtitle: "",
        description: "Черниговская область является одной из крупнейших аграрных областей Украины. В растениеводстве основным направлением является выращивание зерновых. В полесской части области выращивают лен и картофель, а в лесостепной - зерновые и сахарные свеклы. В животноводстве основным является мясо-молочное направление. Активно развивается птицеводство.",
        oblast: "Черниговская область",
        locations: [
            { slug: "koriukivskyy", title: "Корюковский район" },
            { slug: "menskyy", title: "Менский район", parent: "koriukivskyy" },
            { slug: "snovskyy", title: "Сновский район", parent: "koriukivskyy" },
            { slug: "sosnytskyy", title: "Сосницкий район", parent: "koriukivskyy" },
            { slug: "nizhynskyy", title: "Нежинский район" },
            { slug: "baturyn", title: "Батурин", parent: "nizhynskyy" },
            { slug: "bakhmatskyy", title: "Бахмацкий район", parent: "nizhynskyy" },
            { slug: "bobrovytskyy", title: "Бобровицкий район", parent: "nizhynskyy" },
            { slug: "borznyanskyy", title: "Борзнянский район", parent: "nizhynskyy" },
            { slug: "nosivskyy", title: "Носовский район", parent: "nizhynskyy" },
            { slug: "novhorod-siverskyy", title: "Новгород-Северский район" },
            { slug: "koropskyy", title: "Коропский район", parent: "novhorod-siverskyy" },
            { slug: "semenivskyy", title: "Семеновский район", parent: "novhorod-siverskyy" },
            { slug: "prylutskyy", title: "Прилуцкий район" },
            { slug: "varvynskyy", title: "Варвинский район", parent: "prylutskyy" },
            { slug: "ichnyanskyy", title: "Ичнянский район", parent: "prylutskyy" },
            { slug: "sribnyanskyy", title: "Сребнянский район", parent: "prylutskyy" },
            { slug: "talalaivskyy", title: "Талалаевский район", parent: "prylutskyy" },
            { slug: "chernihivskyy", title: "Черниговский район" },
            { slug: "horodnyanskyy", title: "Городнянский район", parent: "chernihivskyy" },
            { slug: "kozeletskyy", title: "Козелецкий район", parent: "chernihivskyy" },
            { slug: "kulikivskyy", title: "Куликовский район", parent: "chernihivskyy" },
            { slug: "ripkynskyy", title: "Репкинский район", parent: "chernihivskyy" },
        ],
    },
    {
        thumbnail: "/images/regions/chrn.jpg",
        title: "Черновцы",
        slug: "chernivtsi",
        mapId: "chernivtsi",
        subtitle: "",
        description:
            "Многоотраслевым является сельское хозяйство Черновицкой области. Наиболее активно здесь выращивают зерновые, сахарные свеклы и картофель, в меньшей степени подсолнечник и овощные культуры. Животноводческие предприятия производят молоко, мясо, яйца и шерсть.",
        oblast: "Черновицкая область",
        locations: [
            { slug: "vyzhnytskyy", title: "Вижницкий район" },
            { slug: "putylskyy", title: "Путильский район", parent: "vyzhnytskyi" },
            { slug: "dnistrovskyy", title: "Днестровский район" },
            { slug: "novodnistrovsk", title: "Новоднестровск", parent: "dnistrovskyy" },
            { slug: "sokyryanskyy", title: "Сокирянский район", parent: "dnistrovskyy" },
            { slug: "khotynskyy", title: "Хотинский район", parent: "dnistrovskyy" },
            { slug: "chernivetskyy", title: "Черновецкий район" },
            { slug: "gertsaivskyy", title: "Герцаевский район", parent: "chernivetskyy" },
            { slug: "glybotskyy", title: "Глыбоцкий район", parent: "chernivetskyy" },
            { slug: "zastavnivskyy", title: "Заставневский район", parent: "chernivetskyy" },
            { slug: "kitsmanskyy", title: "Кицманский район", parent: "chernivetskyy" },
            { slug: "novoselytskyy", title: "Новоселицкий район", parent: "chernivetskyy" },
            { slug: "storozhynetskyy", title: "Сторожинецкий район", parent: "chernivetskyy" },
        ],
    },
    {
        thumbnail: "/images/regions/cr.jpg",
        title: "Крым",
        slug: "krym",
        mapId: "crimea",
        subtitle: "(временно оккупированная территория)",
        description:
            "Выращивание винограда - одна из самых старых отраслей сельского хозяйства республики Крым. Преимущественно это технические сорта, которые используют для приготовления вин, коньяков, соков и т.д.",
        oblast: "АР Крым",
        locations: [
            { slug: "bakhchisarayskiy", title: "Бахчисарайский район" },
            { slug: "belogorskiy", title: "Белогорский район" },
            { slug: "nizhnegorskiy", title: "Нижнегорский район", parent: "belogorskiy" },
            { slug: "dzhankoy", title: "Джанко́йский район" },
            { slug: "evpatoriyskiy", title: "Евпаторийский район" },
            { slug: "chernomorskiy", title: "Черноморский район", parent: "evpatoriyskiy" },
            { slug: "sakiyskiy", title: "Сакский район", parent: "evpatoriyskiy" },
            { slug: "kerchenskiy", title: "Керченский район" },
            { slug: "edykuyskiy", title: "Едикуйский район", parent: "kerchenskiy" },
            { slug: "kurmanskiy", title: "Курманский район" },
            { slug: "pervomayskiy", title: "Первомайский район", parent: "kurmanskiy" },
            { slug: "perekopskiy", title: "Перекопский район" },
            { slug: "rozdolnenskiy", title: "Раздольненский район", parent: "perekopskiy" },
            { slug: "simferopolskiy", title: "Симферопольский район" },
            { slug: "feodosiyskiy", title: "Феодосийский район" },
            { slug: "sudak", title: "Судак", parent: "feodosiyskiy" },
            { slug: "feodosiya", title: "Феодосия", parent: "feodosiyskiy" },
            { slug: "islamteretskiy", title: "Ислям-Терекский район", parent: "feodosiyskiy" },
            { slug: "ichkinskiy", title: "Ичкинский район", parent: "feodosiyskiy" },
            { slug: "yalta", title: "Ялтинский район" },
            { slug: "alushta", title: "Алушта", parent: "yalta" },
        ],
    }
];
const rezObject = {}
for (const i of regionsRU) {
    const o = i.slug
    const arrayRegions = []
    for (const r of i.locations) {
        let myObject = { slug : r.slug, rus: r.title };
        arrayRegions.push(myObject);
    }
    rezObject[o] = arrayRegions
}
const s = JSON.stringify(rezObject)
console.log(s)